@echo off
SET PROJECT_DIR=C:\Users\eljapo22\gephi\network_tool_project

REM Create the main project directory
mkdir %PROJECT_DIR%
cd %PROJECT_DIR%

REM Create the Django project
django-admin startproject network_tool .

REM Create the Django app
django-admin startapp layout

REM Create static and template directories within the app
mkdir layout\static
mkdir layout\static\layout
mkdir layout\static\layout\css
mkdir layout\static\layout\js
mkdir layout\templates
mkdir layout\templates\layout

REM Create initial files
echo "" > layout\static\layout\css\styles.css
echo "" > layout\static\layout\js\script.js
echo "" > layout\templates\layout\index.html

REM Add basic content to index.html
echo ^<html^>^<head^>^<title^>Interactive Network Layout Tool^</title^>^</head^>^<body^>^<h1^>Welcome to the Interactive Network Layout Tool^</h1^>^</body^>^</html^> > layout\templates\layout\index.html

REM Add urls.py content for the app
echo from django.urls import path > layout\urls.py
echo from . import views >> layout\urls.py
echo. >> layout\urls.py
echo urlpatterns = [ >> layout\urls.py
echo     path('', views.index, name='index'), >> layout\urls.py
echo ] >> layout\urls.py

REM Add views.py content for the app
echo from django.shortcuts import render > layout\views.py
echo. >> layout\views.py
echo def index(request): >> layout\views.py
echo     return render(request, 'layout/index.html') >> layout\views.py

REM Add urls.py content for the project
echo from django.contrib import admin > network_tool\urls.py
echo from django.urls import path, include >> network_tool\urls.py
echo. >> network_tool\urls.py
echo urlpatterns = [ >> network_tool\urls.py
echo     path('admin/', admin.site.urls), >> network_tool\urls.py
echo     path('layout/', include('layout.urls')),  ^> Include the layout app URLs >> network_tool\urls.py
echo     path('', include('layout.urls')),  ^> Redirect the root URL to layout app >> network_tool\urls.py
echo ] >> network_tool\urls.py

REM Add settings.py content for the project
echo """ > network_tool\settings.py
echo Django settings for network_tool project. >> network_tool\settings.py
echo >> network_tool\settings.py
echo Generated by 'django-admin startproject' using Django 5.0.8. >> network_tool\settings.py
echo >> network_tool\settings.py
echo For more information on this file, see >> network_tool\settings.py
echo https://docs.djangoproject.com/en/5.0/topics/settings/ >> network_tool\settings.py
echo >> network_tool\settings.py
echo For the full list of settings and their values, see >> network_tool\settings.py
echo https://docs.djangoproject.com/en/5.0/ref/settings/ >> network_tool\settings.py
echo """ >> network_tool\settings.py
echo import os >> network_tool\settings.py
echo from pathlib import Path >> network_tool\settings.py
echo >> network_tool\settings.py
echo # Build paths inside the project like this: BASE_DIR / 'subdir'. >> network_tool\settings.py
echo BASE_DIR = Path(__file__).resolve().parent.parent >> network_tool\settings.py
echo >> network_tool\settings.py
echo # Quick-start development settings - unsuitable for production >> network_tool\settings.py
echo # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/ >> network_tool\settings.py
echo >> network_tool\settings.py
echo # SECURITY WARNING: keep the secret key used in production secret! >> network_tool\settings.py
echo SECRET_KEY = 'django-insecure-z-m%du%zjpq@iv@7bm*w!fpvbw68=_vk&6pixy$as2rsj0x**-' >> network_tool\settings.py
echo >> network_tool\settings.py
echo # SECURITY WARNING: don't run with debug turned on in production! >> network_tool\settings.py
echo DEBUG = True >> network_tool\settings.py
echo >> network_tool\settings.py
echo ALLOWED_HOSTS = [] >> network_tool\settings.py
echo >> network_tool\settings.py
echo # Application definition >> network_tool\settings.py
echo >> network_tool\settings.py
echo INSTALLED_APPS = [ >> network_tool\settings.py
echo     'django.contrib.admin', >> network_tool\settings.py
echo     'django.contrib.auth', >> network_tool\settings.py
echo     'django.contrib.contenttypes', >> network_tool\settings.py
echo     'django.contrib.sessions', >> network_tool\settings.py
echo     'django.contrib.messages', >> network_tool\settings.py
echo     'django.contrib.staticfiles', >> network_tool\settings.py
echo     'layout', >> network_tool\settings.py
echo ] >> network_tool\settings.py
echo >> network_tool\settings.py
echo MIDDLEWARE = [ >> network_tool\settings.py
echo     'django.middleware.security.SecurityMiddleware', >> network_tool\settings.py
echo     'django.contrib.sessions.middleware.SessionMiddleware', >> network_tool\settings.py
echo     'django.middleware.common.CommonMiddleware', >> network_tool\settings.py
echo     'django.middleware.csrf.CsrfViewMiddleware', >> network_tool\settings.py
echo     'django.contrib.auth.middleware.AuthenticationMiddleware', >> network_tool\settings.py
echo     'django.contrib.messages.middleware.MessageMiddleware', >> network_tool\settings.py
echo     'django.middleware.clickjacking.XFrameOptionsMiddleware', >> network_tool\settings.py
echo ] >> network_tool\settings.py
echo >> network_tool\settings.py
echo ROOT_URLCONF = 'network_tool.urls' >> network_tool\settings.py
echo >> network_tool\settings.py
echo TEMPLATES = [ >> network_tool\settings.py
echo     { >> network_tool\settings.py
echo         'BACKEND': 'django.template.backends.django.DjangoTemplates', >> network_tool\settings.py
echo         'DIRS': [BASE_DIR / 'layout' / 'templates'], >> network_tool\settings.py
echo         'APP_DIRS': True, >> network_tool\settings.py
echo         'OPTIONS': { >> network_tool\settings.py
echo             'context_processors': [ >> network_tool\settings.py
echo                 'django.template.context_processors.debug', >> network_tool\settings.py
echo                 'django.template.context_processors.request', >> network_tool\settings.py
echo                 'django.contrib.auth.context_processors.auth', >> network_tool\settings.py
echo                 'django.contrib.messages.context_processors.messages', >> network_tool\settings.py
echo             ], >> network_tool\settings.py
echo         }, >> network_tool\settings.py
echo     }, >> network_tool\settings.py
echo ] >> network_tool\settings.py
echo >> network_tool\settings.py
echo WSGI_APPLICATION = 'network_tool.wsgi.application' >> network_tool\settings.py
echo >> network_tool\settings.py
echo # Database >> network_tool\settings.py
echo # https://docs.djangoproject.com/en/5.0/ref/settings/#databases >> network_tool\settings.py
echo >> network_tool\settings.py
echo DATABASES = { >> network_tool\settings.py
echo     'default': { >> network_tool\settings.py
echo         'ENGINE': 'django.db.backends.sqlite3', >> network_tool\settings.py
echo         'NAME': BASE_DIR / 'db.sqlite3', >> network_tool\settings.py
echo     } >> network_tool\settings.py
echo } >> network_tool\settings.py
echo >> network_tool\settings.py
echo # Password validation >> network_tool\settings.py
echo # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators >> network_tool\settings.py
echo >> network_tool\settings.py
echo AUTH_PASSWORD_VALIDATORS = [ >> network_tool\settings.py
echo     { >> network_tool\settings.py
echo         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', >> network_tool\settings.py
echo     }, >> network_tool\settings.py
echo     { >> network_tool\settings.py
echo         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', >> network_tool\settings.py
echo     }, >> network_tool\settings.py
echo     { >> network_tool\settings.py
echo         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', >> network_tool\settings.py
echo     }, >> network_tool\settings.py
echo     { >> network_tool\settings.py
echo         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', >> network_tool\settings.py
echo     }, >> network_tool\settings.py
echo ] >> network_tool\settings.py
echo >> network_tool\settings.py
echo # Internationalization >> network_tool\settings.py
echo # https://docs.djangoproject.com/en/5.0/topics/i18n/ >> network_tool\settings.py
echo >> network_tool\settings.py
echo LANGUAGE_CODE = 'en-us' >> network_tool\settings.py
echo >> network_tool\settings.py
echo TIME_ZONE = 'UTC' >> network_tool\settings.py
echo >> network_tool\settings.py
echo USE_I18N = True >> network_tool\settings.py
echo >> network_tool\settings.py
echo USE_TZ = True >> network_tool\settings.py
echo >> network_tool\settings.py
echo # Static files (CSS, JavaScript, Images) >> network_tool\settings.py
echo # https://docs.djangoproject.com/en/5.0/howto/static-files/ >> network_tool\settings.py
echo >> network_tool\settings.py
echo STATIC_URL = 'static/' >> network_tool\settings.py
echo >> network_tool\settings.py
echo STATICFILES_DIRS = [BASE_DIR / 'layout' / 'static'] >> network_tool\settings.py
echo >> network_tool\settings.py
echo # Default primary key field type >> network_tool\settings.py
echo # https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field >> network_tool\settings.py
echo >> network_tool\settings.py
echo DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' >> network_tool\settings.py

REM Apply migrations
python manage.py makemigrations
python manage.py migrate

REM Collect static files
python manage.py collectstatic --noinput

REM Start the development server
python manage.py runserver

pause
